let lessons = [
  {
    id: 01,
    course: "Angular",
    level: "Advance Level",
    price: 500,
    image: "assets/images/logo/angu.jpg",
    availableInventory: 5,
    rating: 3,
  },
  {
    id: 02,
    course: "Ios Developemnt",
    level: "Beginer Course",
    price: 650,
    image: "assets/images/logo/ios.jpeg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 03,
    course: "Photoshop",
    level: "Intermidiate ",
    price: 100,
    image: "assets/images/logo/ps.jpg",
    availableInventory: 5,
    rating: 5,
  },
  {
    id: 04,
    course: "invision",
    level: "Beginer ",
    price: 150,
    image: "assets/images/logo/ps.jpg",
    availableInventory: 5,
    rating: 3,
  },
  {
    id: 05,
    course: "Wordpress",
    level: "Beginer ",
    price: 200,
    image: "assets/images/logo/wp.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 06,
    course: "ReactJs",
    level: "Advane Course ",
    price: 350,
    image: "assets/images/logo/react.png",
    availableInventory: 5,
    rating: 5,
  },
  {
    id: 07,
    course: "NodeJs",
    level: "Advance",
    price: 170,
    image: "assets/images/logo/node.png",
    availableInventory: 5,
    rating: 3,
  },
  {
    id: 08,
    course: "Aungular Testing",
    level: "Profesional",
    price: 240,
    image: "assets/images/logo/react.png",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 09,
    course: "TypeScript",
    level: "Learners Course",
    price: 190,
    image: "assets/images/logo/ts.jpg",
    availableInventory: 5,
    rating: 5,
  },
  {
    id: 010,
    course: "JavaScript",
    level: "Beginer to Advance ",
    price: 200,
    image: "assets/images/logo/js.png",
    availableInventory: 5,
    rating: 3,
  },
  {
    id: 011,
    course: "Dev Ops",
    level: "Advance Course",
    price: 300,
    image: "assets/images/logo/dev.jpeg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 012,
    course: "C#",
    level: "Profesional ",
    price: 260,
    image: "assets/images/logo/csharp.png",
    availableInventory: 5,
    rating: 5,
  },
];
