let courses = [
  {
    id: 01,
    course: "Angular",
    location: "Mauritius",
    price: 500,
    image: "img/accounting.jpg",
    availableInventory: 5,
    rating: 3,
  },
  {
    id: 02,
    course: "Ios Developemnt",
    location: "Dubai",
    price: 650,
    image: "img/chemistry.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 03,
    course: "Photoshop",
    location: "Hendon",
    price: 100,
    image: "img/biology.jpg",
    availableInventory: 5,
    rating: 5,
  },
  {
    id: 04,
    course: "invision",
    location: "Mauritius",
    price: 150,
    image: "img/government.jpg",
    availableInventory: 5,
    rating: 3,
  },
  {
    id: 05,
    course: "Wordpress",
    location: "Dubai",
    price: 200,
    image: "img/english.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 06,
    course: "ReactJs",
    location: "Hendon",
    price: 350,
    image: "img/law.jpg",
    availableInventory: 5,
    rating: 5,
  },
  {
    id: 07,
    course: "NodeJs",
    location: "Mauritius",
    price: 170,
    image: "img/history.jpg",
    availableInventory: 5,
    rating: 3,
  },
  {
    id: 08,
    course: "Aungular Testing",
    location: "Dubai",
    price: 240,
    image: "img/science.jpg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 09,
    course: "TypeScript",
    location: "Hendon",
    price: 190,
    image: "img/math.jpg",
    availableInventory: 5,
    rating: 5,
  },
  {
    id: 010,
    course: "JavaScript",
    location: "Mauritius",
    price: 200,
    image: "img/demo-img.svg",
    availableInventory: 5,
    rating: 3,
  },
  {
    id: 011,
    course: "Dev Ops",
    location: "Dubai",
    price: 300,
    image: "img/demo-img.svg",
    availableInventory: 5,
    rating: 4,
  },
  {
    id: 012,
    course: "C#",
    Lecture: "Bur Dubai",
    price: 260,
    image: "img/demo-img.svg",
    availableInventory: 5,
    rating: 5,
  },
];
